### ISSUE TITLE
Support missing for some markdown formatting options

### ISSUE THREAD

**Issue by brianclements** [progrium/viewdocs#29] opened 2014-06-03 16:23 UTC
Using the default template supplied in the repo, it seems that the following markdown options don't make their way into the final html page:

* bold text using \*\*this\*\* format
* nested items using
    * 4 spaces
        * then a \*

**Comment by josegonzalez** [comment] 2015-12-04 05:31
Duplicate of #22. Closing in favor of continuing discussion there.

**Closed by josegonzalez** 2015-12-04 05:31 UTC
