### ISSUE TITLE
Known issue: Read-only task lists are not supported, even though GitHub now renders it for all Markdown documents

### ISSUE THREAD

**Issue by maxlinc** [progrium/viewdocs#32] opened 2014-10-28 23:07 UTC
I thought I'd document a known issue even though I don't think there's much you can do about this unless you want to switch to a markdown engine w/ GFM support rather than GitHub's Markdown API (also suggested in #22).

GitHub previously only supported task lists in issues and commit comments, but now they work in all documents - including README.md. It'd be great to see the same behavior in viewdocs.

Grip [explains](https://github.com/joeyespo/grip#known-issues):
> GitHub introduced read-only task lists to all Markdown documents in
      repositories and wikis [back in April][task-lists], but
      [the API][markdown] doesn't respect this yet.

[task-lists]: https://github.com/blog/1825-task-lists-in-all-markdown-documents
[markdown]: http://developer.github.com/v3/markdown

**Comment by josegonzalez** [comment] 2015-12-04 05:30
Duplicate of #22. Closing in favor of continuing discussion there.

**Closed by josegonzalez** 2015-12-04 05:30 UTC
